services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres # Changed database service name
    environment:
      DB_CONNECTION: pgsql # Set the correct DB connection
      DB_HOST: postgres # Use the service name as the hostname
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-your_database_name} # Use environment variable or default
      DB_USERNAME: ${DB_USERNAME:-your_db_user}
      DB_PASSWORD: ${DB_PASSWORD:-your_db_password}
    networks:
      - app-network

  postgres: # PostgreSQL service definition
    image: postgres:17 # Or your preferred version
    environment:
      POSTGRES_USER: ${DB_USERNAME:-your_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_db_password}
      POSTGRES_DB: ${DB_DATABASE:-your_database_name}
    ports:
      - "5432:5432" # Expose the port for external connections (optional, but useful for debugging)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across container restarts
    networks:
      - app-network

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence

networks:
  app-network:
    driver: bridge