name: CI/CD for Laravel

on:
  push:
    branches:
      - main # Runs on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Replace with your PHP version
        extensions: mbstring, pdo, bcmath, intl
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest

    - name: Setup Laravel Environment
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --seed

    - name: Run Tests
      run: php artisan test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Production
      run: |
        echo "Add your deployment script here"
        # Example for deploying to a server
        ssh user@your-server 'cd /path/to/project && git pull origin main && composer install --no-dev && php artisan migrate --force && php artisan cache:clear && php artisan config:clear && php artisan route:cache && php artisan view:clear'
